#This line define how we are going to trigger the pipeline

trigger: none

variables:
    dockerRegistryServiceConnection: 'mediawikiclusterregistry'
    imageRepository: 'mediawiki'
    dockerfilePath: $(Build.SourcesDirectory)/mediawiki-1.41.1'
    containerRegistry: 'mediawikiclusterregistry.azurecr.io'


stages:
 -  stage: Build
    displayName: Build and publish stage
    jobs:
    job: Build
    displayName: Build job
    pool:
      name: 'mediawiki'
    steps:
    - task: DockerInstaller@e
      inputs:
        dockerVersion: 17.09.0-ce

    - task: Bash@3
      displayName: Git Short Commitin
      inputs:
        targetlyne: "inline"
        script:
          buildsha-$(git rev-parse-short-7 HEAD)
          
    - task: Docker@z
      displayName: Build and publish image to Azure Container Registry
      inputs:
        command: buildAndPush
        containerkegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilelpath)
        tags: |
          $(imageTag)


stage: Kubernetes Helm
displayName: Kuberentes Helm
dependson: []
jobs:
- job: Helm
  displayName: Helm job
  pool:
    name: 'mediawiki'
  steps:
  - task: Copyfiles@2
    inputs:
       sourcefolder: mediawiki-1.41.1
       contents: |
          mediawiki-1.41.1/charts/*
          mediawiki-1.41.1/templates/*
        targetFolder: '$(Build ArtifactStaging Directory)'
  - task: PublishBuildArtifacts@l
    inputs:
      pathToPublish: 'S(Build ArtifactStaging@irectory)'
      Artifactname: helm_package
