replicaCount: 1

image:
  repository: my-registry/mediawiki
  tag: "1.41.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: mediawiki.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: []

mysql:
  enabled: true
  image: mariadb:10.5
  database: mediawiki
  user: mediawiki
  password: mediawiki-password
  rootPassword: root-password
  service:
    port: 3306
  persistence:
    enabled: true
    size: 8Gi
